name: GitHub to Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]

jobs:
  discordNotify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            📢 **GitHub Update**  
            **Branch:** ${{ github.ref_name }}  
            **Commit by:** ${{ github.actor }}  
            **Commit message:** ${{ github.event.head_commit.message }}  
