name: GitHub to Discord
on: [push, pull_request]

jobs:
  discordNotify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "New update in the repository! 🚀"
